package docs

import (
	swagger "github.com/arsmn/fiber-swagger/v2"
	"go.uber.org/fx"

	// docs are generated by Swag CLI, you have to import them.
	// replace with your own docs folder, usually "github.com/username/reponame/docs"
	"github.com/gofiber/fiber/v2"
)

var Module = fx.Invoke(
	func(app *fiber.App) {
		app.Get("/swagger/*", swagger.HandlerDefault)
	},
)
