basePath: /
definitions:
  fiber.Error:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  github_com_IN-45_INT20H-test-task_modules_storage_internal_service.DtoRecipe:
    properties:
      author_id:
        type: string
      cooking_time_minutes:
        type: integer
      description:
        type: string
      id:
        type: string
      image_url:
        type: string
      instructions:
        items:
          $ref: '#/definitions/github_com_IN-45_INT20H-test-task_modules_storage_internal_service.dtoInstruction'
        type: array
      name:
        type: string
      products:
        items:
          $ref: '#/definitions/github_com_IN-45_INT20H-test-task_modules_storage_internal_service.dtoProduct'
        type: array
    type: object
  github_com_IN-45_INT20H-test-task_modules_storage_internal_service.dtoInstruction:
    properties:
      description:
        type: string
      priority:
        type: integer
    type: object
  github_com_IN-45_INT20H-test-task_modules_storage_internal_service.dtoProduct:
    properties:
      amount:
        type: integer
      amount_type:
        type: string
      category_id:
        type: string
      image_url:
        type: string
      name:
        type: string
      product_id:
        type: string
    type: object
  github_com_IN-45_INT20H-test-task_pkg_customerrors.UnauthorizedError:
    type: object
  modules_storage_internal_handler.dtoCategory:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  modules_storage_internal_handler.dtoCreateCategory:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  modules_storage_internal_handler.dtoCreateInstruction:
    properties:
      description:
        type: string
      priority:
        type: integer
    required:
    - priority
    type: object
  modules_storage_internal_handler.dtoCreateInventory:
    properties:
      amount:
        type: integer
      amount_type:
        type: string
      product_id:
        type: string
    required:
    - product_id
    type: object
  modules_storage_internal_handler.dtoCreateProduct:
    properties:
      amount_type:
        type: string
      category_id:
        type: string
      image_url:
        type: string
      name:
        type: string
    required:
    - category_id
    - name
    type: object
  modules_storage_internal_handler.dtoCreateRecipe:
    properties:
      cooking_time_minutes:
        type: integer
      description:
        type: string
      image_url:
        type: string
      instructions:
        items:
          $ref: '#/definitions/modules_storage_internal_handler.dtoCreateInstruction'
        type: array
      name:
        type: string
      products:
        items:
          $ref: '#/definitions/modules_storage_internal_handler.dtoCreateRecipesProducts'
        type: array
    required:
    - name
    type: object
  modules_storage_internal_handler.dtoCreateRecipesProducts:
    properties:
      amount:
        type: integer
      amount_type:
        type: string
      product_id:
        type: string
    required:
    - amount
    - amount_type
    - product_id
    type: object
  modules_storage_internal_handler.dtoInventory:
    properties:
      amount:
        type: integer
      amount_type:
        type: string
      product_id:
        type: string
    type: object
  modules_storage_internal_handler.dtoProduct:
    properties:
      amount_type:
        type: string
      category:
        type: string
      id:
        type: string
      image_url:
        type: string
      name:
        type: string
    type: object
  modules_storage_internal_handler.dtoUploadedFile:
    properties:
      file_url:
        type: string
    type: object
  modules_user_internal_handler.dtoAuth:
    properties:
      email:
        type: string
      password:
        maxLength: 255
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
host: localhost:8000
info:
  contact: {}
  title: Backend API
paths:
  /categories:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/modules_storage_internal_handler.dtoCategory'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_IN-45_INT20H-test-task_pkg_customerrors.UnauthorizedError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Get all categories
      tags:
      - Category
  /category:
    post:
      parameters:
      - description: Category
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/modules_storage_internal_handler.dtoCreateCategory'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_IN-45_INT20H-test-task_pkg_customerrors.UnauthorizedError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Create new category
      tags:
      - Category
  /inventory:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/modules_storage_internal_handler.dtoInventory'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_IN-45_INT20H-test-task_pkg_customerrors.UnauthorizedError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Get all inventory products
      tags:
      - Inventory
    post:
      parameters:
      - description: Inventory
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/modules_storage_internal_handler.dtoCreateInventory'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_IN-45_INT20H-test-task_pkg_customerrors.UnauthorizedError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Add product to inventory
      tags:
      - Inventory
  /product:
    post:
      parameters:
      - description: Product
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/modules_storage_internal_handler.dtoCreateProduct'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_IN-45_INT20H-test-task_pkg_customerrors.UnauthorizedError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Create new product
      tags:
      - Product
  /product/{id}:
    get:
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/modules_storage_internal_handler.dtoProduct'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_IN-45_INT20H-test-task_pkg_customerrors.UnauthorizedError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Get product by id
      tags:
      - Product
  /products:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/modules_storage_internal_handler.dtoProduct'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_IN-45_INT20H-test-task_pkg_customerrors.UnauthorizedError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Get all products
      tags:
      - Product
  /recipe:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_IN-45_INT20H-test-task_modules_storage_internal_service.DtoRecipe'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_IN-45_INT20H-test-task_pkg_customerrors.UnauthorizedError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Get all recipes
      tags:
      - Recipe
    post:
      parameters:
      - description: Recipe
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/modules_storage_internal_handler.dtoCreateRecipe'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_IN-45_INT20H-test-task_pkg_customerrors.UnauthorizedError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Create recipe and add products and instructions
      tags:
      - Recipe
  /sign-in:
    post:
      consumes:
      - application/json
      parameters:
      - description: User credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/modules_user_internal_handler.dtoAuth'
      responses:
        "200":
          description: Saves token to cookie
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Sign in to account
      tags:
      - Authentication
  /sign-up:
    post:
      consumes:
      - application/json
      parameters:
      - description: User credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/modules_user_internal_handler.dtoAuth'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Sign up into account
      tags:
      - Authentication
  /upload:
    post:
      parameters:
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modules_storage_internal_handler.dtoUploadedFile'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_IN-45_INT20H-test-task_pkg_customerrors.UnauthorizedError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Upload file to cloud storage
      tags:
      - Files Uploading
swagger: "2.0"
